app:
  appName: test
  namespace: frontend
  environment: prod
  team: frontend

  image:
    registry: docker.io
    name: reisraff/test
    tag: latest
    pullPolicy: IfNotPresent
    containerPort: 3000

  env:
    TEST: "foo"

  logs:
    enabled: false

  ingress:
    domain: fqs.reisraff.local
    scheme: public
    name: test-public
    additionalHostnames: []
    paths:
    - /

  service:
    enabled: true
    type: NodePort
    port: 80

  resources:
    limits:
      cpu: 200m
      memory: 300Mi
    requests:
      cpu: 200m
      memory: 200Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage:
    targetMemoryUtilizationPercentage:

  livenessProbe:
    enabled: true
    http:
      path: /
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 3
    successThreshould: 1
    failureThreshould: 3
